"""Create table analytic

Revision ID: 2da90543ccba
Revises: 532a8a2a3741
Create Date: 2026-05-22 11:41:27.151746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2da90543ccba'
down_revision: Union[str, Sequence[str], None] = '532a8a2a3741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyticmodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('total_tasks_created', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usermodel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_task_user_status_created'), 'task', ['user_id', 'status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_task_user_priority_created'), 'task', ['user_id', 'priority', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_task_user_id'), 'task', ['user_id'], unique=False)
    op.create_index(op.f('idx_task_user_created'), 'task', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_task_status'), 'task', ['status'], unique=False)
    op.create_index(op.f('idx_task_priority'), 'task', ['priority'], unique=False)
    op.drop_table('analyticmodel')
    # ### end Alembic commands ###
