"""Create Audit Log Table

Revision ID: 532a8a2a3741
Revises: b4973b3f0159
Create Date: 2026-05-19 11:58:46.657116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '532a8a2a3741'
down_revision: Union[str, Sequence[str], None] = 'b4973b3f0159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('payload', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usermodel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_task_user_status_created'), 'task', ['user_id', 'status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_task_user_priority_created'), 'task', ['user_id', 'priority', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_task_user_id'), 'task', ['user_id'], unique=False)
    op.create_index(op.f('idx_task_user_created'), 'task', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_task_status'), 'task', ['status'], unique=False)
    op.create_index(op.f('idx_task_priority'), 'task', ['priority'], unique=False)
    op.drop_table('auditlog')
    # ### end Alembic commands ###
