"""Create table notification

Revision ID: 5cfd91060656
Revises: afde5234243e
Create Date: 2026-05-26 12:02:42.974342

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "5cfd91060656"
down_revision: Union[str, Sequence[str], None] = "afde5234243e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notificationmodel",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["usermodel.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("idx_task_user_status_created"),
        "task",
        ["user_id", "status", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_task_user_priority_created"),
        "task",
        ["user_id", "priority", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(op.f("idx_task_user_id"), "task", ["user_id"], unique=False)
    op.create_index(
        op.f("idx_task_user_created"),
        "task",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(op.f("idx_task_status"), "task", ["status"], unique=False)
    op.create_index(op.f("idx_task_priority"), "task", ["priority"], unique=False)
    op.drop_table("notificationmodel")
    # ### end Alembic commands ###
