"""Add new field updated_at table analytic

Revision ID: a9597459121c
Revises: 2da90543ccba
Create Date: 2026-05-22 11:44:31.609097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9597459121c'
down_revision: Union[str, Sequence[str], None] = '2da90543ccba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyticmodel', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_task_user_status_created'), 'task', ['user_id', 'status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_task_user_priority_created'), 'task', ['user_id', 'priority', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_task_user_id'), 'task', ['user_id'], unique=False)
    op.create_index(op.f('idx_task_user_created'), 'task', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_task_status'), 'task', ['status'], unique=False)
    op.create_index(op.f('idx_task_priority'), 'task', ['priority'], unique=False)
    op.drop_column('analyticmodel', 'updated_at')
    # ### end Alembic commands ###
