"""Update field total_tasks_created table AnalyticModel

Revision ID: afde5234243e
Revises: a9597459121c
Create Date: 2026-05-25 15:07:03.659544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afde5234243e'
down_revision: Union[str, Sequence[str], None] = 'a9597459121c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'analyticmodel', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_task_user_status_created'), 'task', ['user_id', 'status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_task_user_priority_created'), 'task', ['user_id', 'priority', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_task_user_id'), 'task', ['user_id'], unique=False)
    op.create_index(op.f('idx_task_user_created'), 'task', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_task_status'), 'task', ['status'], unique=False)
    op.create_index(op.f('idx_task_priority'), 'task', ['priority'], unique=False)
    op.drop_constraint(None, 'analyticmodel', type_='unique')
    # ### end Alembic commands ###
