"""Add field priority in Class Task

Revision ID: bab1f1192407
Revises: 0d65fa1d965c
Create Date: 2026-03-26 12:53:12.307042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bab1f1192407'
down_revision: Union[str, Sequence[str], None] = '0d65fa1d965c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('priority', sa.Integer(), nullable=True))
    op.execute("UPDATE task SET priority = 0")
    op.alter_column('task', 'priority', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'priority')
    # ### end Alembic commands ###
