"""add description field

Revision ID: cc077322d4e1
Revises: bab1f1192407
Create Date: 2026-03-26 13:19:01.075235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc077322d4e1'
down_revision: Union[str, Sequence[str], None] = 'bab1f1192407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('description', sa.String(), nullable=True))

    op.execute("""
        UPDATE task 
        SET description = 'Study hard, work hard, learning is very important!!!'
        WHERE description IS NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('task', 'description')
    # ### end Alembic commands ###
