"""Change type user_id in table Refresh token

Revision ID: d6ab01ce7317
Revises: 23c1ea8d906c
Create Date: 2026-04-03 14:23:13.705382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6ab01ce7317'
down_revision: Union[str, Sequence[str], None] = '23c1ea8d906c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refreshtokenmodel_new",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False, default=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
    )

    # 2. Copy data từ bảng cũ
    op.execute("""
        INSERT INTO refreshtokenmodel_new (id, user_id, token, is_revoked, expires_at)
        SELECT id, user_id, token, is_revoked, expires_at
        FROM refreshtokenmodel
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('task', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'refreshtokenmodel', type_='foreignkey')
    op.alter_column('refreshtokenmodel', 'user_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
