"""Update field dealine

Revision ID: fd1bb814c62a
Revises: cc077322d4e1
Create Date: 2026-03-26 14:01:06.731892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from datetime import datetime, timedelta, timezone


# revision identifiers, used by Alembic.
revision: str = 'fd1bb814c62a'
down_revision: Union[str, Sequence[str], None] = 'cc077322d4e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('deadline', sa.DateTime(), nullable=True))
    future_time = (datetime.now(timezone.utc) + timedelta(days=7)).strftime("%Y-%m-%d %H:%M:%S")

    op.execute(f"""
        UPDATE task 
        SET deadline = '{future_time}'
        WHERE deadline IS NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('task', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('task', 'deadline')
    # ### end Alembic commands ###
