"""add embedding column

Revision ID: 7185a45ecb9d
Revises: 9be1f3fbf9c9
Create Date: 2026-08-07 09:40:14.224927

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision: str = "7185a45ecb9d"
down_revision: Union[str, Sequence[str], None] = "9be1f3fbf9c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "memories",
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("memories", "embedding")
    # ### end Alembic commands ###
